/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "on-tertiary-container": "#d0d3d5",
        "on-primary-fixed-variant": "#293ca0",
        "background": "#f9f9fc",
        "tertiary-fixed": "#e0e3e6",
        "on-primary-fixed": "#00105c",
        "error": "#ba1a1a",
        "surface-container": "#eeeef0",
        "primary-container": "#3f51b5",
        "tertiary": "#404346",
        "on-primary-container": "#cacfff",
        "surface-container-highest": "#e2e2e5",
        "on-surface-variant": "#454652",
        "error-container": "#ffdad6",
        "on-surface": "#1a1c1e",
        "secondary-fixed": "#a1efff",
        "primary-fixed": "#dee0ff",
        "outline-variant": "#c5c5d4",
        "surface-container-low": "#f3f3f6",
        "surface-container-lowest": "#ffffff",
        "tertiary-container": "#585b5d",
        "on-tertiary-fixed-variant": "#44474a",
        "secondary-container": "#58e6ff",
        "inverse-primary": "#bac3ff",
        "outline": "#757684",
        "surface": "#f9f9fc",
        "on-secondary": "#ffffff",
        "inverse-surface": "#2f3133",
        "primary-fixed-dim": "#bac3ff",
        "surface-variant": "#e2e2e5",
        "surface-dim": "#dadadc",
        "on-primary": "#ffffff",
        "inverse-on-surface": "#f0f0f3",
        "primary": "#24389c",
        "on-secondary-fixed-variant": "#004e59",
        "on-error-container": "#93000a",
        "on-error": "#ffffff",
        "on-background": "#1a1c1e",
        "surface-bright": "#f9f9fc",
        "secondary-fixed-dim": "#44d8f1",
        "secondary": "#006876",
        "on-secondary-fixed": "#001f25",
        "on-tertiary-fixed": "#191c1e",
        "on-tertiary": "#ffffff",
        "surface-tint": "#4355b9",
        "on-secondary-container": "#006573",
        "surface-container-high": "#e8e8ea",
        "tertiary-fixed-dim": "#c4c7ca"
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px"
      },
      spacing: {
        "xs": "4px",
        "gutter": "24px",
        "base": "4px",
        "xl": "32px",
        "lg": "24px",
        "2xl": "48px",
        "3xl": "64px",
        "sm": "8px",
        "container-max": "1280px",
        "md": "16px"
      },
      fontFamily: {
        "headline-lg": ["Inter", "sans-serif"],
        "body-lg": ["Inter", "sans-serif"],
        "body-md": ["Inter", "sans-serif"],
        "title-md": ["Inter", "sans-serif"],
        "label-md": ["Inter", "sans-serif"],
        "display-lg": ["Inter", "sans-serif"]
      }
    },
  },
  plugins: [],
}
